[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mpl_core_anchor_examples = "GD7rkX6ARmc4SZSVTCTURggAHXAHVEyeTG3bNtcUZZAE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
